### ISSUE TITLE
'meteor/random'

### ISSUE THREAD

**Issue by hkalic** [abhiaiyer91/meteor-apollo-counter#1]
Why did you use? 

> in _schema.js_ (https://github.com/abhiaiyer91/meteor-apollo-counter/blob/805186d5dcaa03f047ce50383c13164cecfa87b2/imports/data/schema.js#L1)

`import { Random } from 'meteor/random';`

**Comment by abhiaiyer91** [comment]
Eh leftover from my boilerplate, I'll remove thanks
