### ISSUE TITLE
graphiql problem: Cannot GET /

### ISSUE THREAD

**Issue by tintoverano** [abhiaiyer91/meteor-apollo-counter#2]
hi @abhiaiyer91,

thanks for the example!!

the app itself runs fine, but graphiql on localhost:4000 prints the following message in the browser window:

```
Cannot GET /
```

console is empty, no messages there

meteor, npm are both up-to-date

what do you think what the problem could be?

cheers,

tinto

**Comment by abhiaiyer91** [comment]
Head to localhost:4000/graphql

let me know if that works for you! If it does, want to put that in the README?

**Comment by tintoverano** [comment]
yes, it works this way, thanks

sure, will do a PR for the README
